name: PermissionPlus
main: PermissionPlus\PermissionPlus
version: 1.8.0
api: [3.0.0]
load: STARTUP
author: Hmy2001
authors:
  - deceitya
commands:
 pp:
  description: PermissionPlus help
 ppplayer:
  aliases: [ppplyr]
  description: Manages player permission
 ppcommand:
  aliases: [ppcmd]
  description: Manages player permission
 ppsub:
  description: PermissionPlus preferences
 ppcmdall:
  aliases: [ppca]
  description: Manages player permission
 ppconfig:
  aliases: [ppcfg]
  description: PermissionPlus preferences
 ppsort:
  description: PermissionPlus preferences