name: PermissionPlus
main: PermissionPlus\PermissionPlus
version: 1.5.8
api: [3.0.0-ALPHA11]
load: STARTUP
author: Hmy2001
commands:
 pp:
  aliases: [pp]
  description: PermissionPlus help
 ppplayer:
  aliases: [ppplyr]
  description: Manages player permission
 ppcommand:
  aliases: [ppcmd]
  description: Manages player permission
 ppsub:
  description: PermissionPlus preferences
 ppconfig:
  aliases: [ppcfg]
  description: PermissionPlus preferences